//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 04:46:11 PM ICT 
//


package com.paperpark.categories_mapping;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CategoryMappings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoryMappings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="categoryMapping" type="{http://www.guitarpark.com/schema/categories-mapping}CategoryMapping" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryMappings", propOrder = {
    "categoryMapping"
})
@XmlRootElement(name = "categoryMappings")
public class CategoryMappings {

    protected List<CategoryMapping> categoryMapping;

    /**
     * Gets the value of the categoryMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoryMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryMapping }
     * 
     * 
     */
    public List<CategoryMapping> getCategoryMapping() {
        if (categoryMapping == null) {
            categoryMapping = new ArrayList<CategoryMapping>();
        }
        return this.categoryMapping;
    }

    private static final String CATEGORY_MAPPING_FILE
            = "WEB-INF\\configs\\category\\categories-mapping.xml";
   
    public synchronized static CategoryMappings getCategoryMappings(String realPath) {
        try {
            JAXBContext context = JAXBContext.newInstance(CategoryMappings.class);
            Unmarshaller un = context.createUnmarshaller();
            
            String filePath = realPath + CATEGORY_MAPPING_FILE;
            
            File file = new File(filePath);
            
            CategoryMappings mappings = (CategoryMappings) un.unmarshal(file);
            
            if (mappings != null) {
                return mappings;
            }
        } catch (JAXBException ex) {
            Logger.getLogger(CategoryMappings.class.getName()).log(Level.SEVERE, null, ex);
        }
        return new CategoryMappings();
    }
}
