//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 04:46:11 PM ICT 
//


package com.paperpark.categories_mapping;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.guitarpark.schema.categories_mapping package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CategoryMappings_QNAME = new QName("http://www.guitarpark.com/schema/categories-mapping", "categoryMappings");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.guitarpark.schema.categories_mapping
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CategoryMappings }
     * 
     */
    public CategoryMappings createCategoryMappings() {
        return new CategoryMappings();
    }

    /**
     * Create an instance of {@link CategoryMapping }
     * 
     */
    public CategoryMapping createCategoryMapping() {
        return new CategoryMapping();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryMappings }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.guitarpark.com/schema/categories-mapping", name = "categoryMappings")
    public JAXBElement<CategoryMappings> createCategoryMappings(CategoryMappings value) {
        return new JAXBElement<CategoryMappings>(_CategoryMappings_QNAME, CategoryMappings.class, null, value);
    }

}
