//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 04:46:11 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.guitarpark.com/schema/categories-mapping", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.paperpark.categories_mapping;
