//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 02:49:40 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.guitarpark.com/schema/estimation-for-model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.paperpark.config.model;
