//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.03 at 02:19:28 AM ICT 
//


package com.paperpark.config.crawler;

import com.paperpark.listener.PaperParkContextListener;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CrawlerConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CrawlerConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="enableCrawler" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CrawlerConfig", propOrder = {
    "enableCrawler"
})
@XmlRootElement(name = "configs")
public class CrawlerConfig {

    public CrawlerConfig() {
        this.enableCrawler = true;
    }
    
    protected boolean enableCrawler;

    /**
     * Gets the value of the enableCrawler property.
     * 
     */
    public boolean isEnableCrawler() {
        return enableCrawler;
    }

    /**
     * Sets the value of the enableCrawler property.
     * 
     */
    public void setEnableCrawler(boolean value) {
        this.enableCrawler = value;
    }
    
    private static final String CRAWLER_CONFIG_FILE
            = "WEB-INF\\configs\\crawler\\crawler-config.xml";

    public synchronized static CrawlerConfig getCrawlerConfig(String realPath) {
        try {
            JAXBContext context = JAXBContext.newInstance(CrawlerConfig.class);
            Unmarshaller un = context.createUnmarshaller();
            
            String filePath = realPath + CRAWLER_CONFIG_FILE;
            
            File file = new File(filePath);
            
            CrawlerConfig config = (CrawlerConfig) un.unmarshal(file);
            
            return config;
        } catch (JAXBException ex) {
            Logger.getLogger(PaperParkContextListener.class.getName()).log(Level.SEVERE, null, ex);
        }
        return new CrawlerConfig();
    }
}
